export PATH="$HOME/dotfiles/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$$HOME/.uv/bin:$PATH"
export PATH="$PATH:/Users/ryohei/.lmstudio/bin"
. "$HOME/.local/bin/env"
